Youtube Demo/src/objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Support_Email__c</fullName>
        <label>Support Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Support_Phone__c</fullName>
        <label>Support Phone</label>
        <type>Phone</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Youtube Demo/src/objects/Release_Window_Config__c.object
<CustomObject>
    <fields>
        <fullName>Release_End_Date__c</fullName>
        <label>Release End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Release_Start_Date__c</fullName>
        <label>Release Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Release Window Config</label>
    <nameField>
        <label>Release Window Config ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Release Window Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Youtube Demo/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>EU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Youtube Demo/src/classes/UserMaintenanceController.cls
public class UserMaintenanceController {

    public Region__c region{get;set;}
     public Release_Window_Config__c releaseWindow{get;set;}
    
    public UserMaintenanceController(){
        setRegion();
        setMaintenance();
    }
    
    void setRegion(){
           User u= [SELECT Region__c FROM User where Id=:UserInfo.getuserid()];
           region = [SELECT Support_Phone__c,Support_Email__c FROM  Region__c WHERE Name = :u.Region__c];           
    }
    void setMaintenance(){
           releaseWindow =[SELECT Release_Start_Date__c,Release_End_Date__c FROM Release_Window_Config__c];
    }
    public String getLocale() {
        return UserInfo.getlocale();
    }
     public string getPhone(){
     return region.Support_Phone__c;
    }
    
     public string getEmail(){
     return region.Support_Email__c;
    }
    
     public string getMaintainenceStartDate() {
          
            return releaseWindow.Release_Start_Date__c.format();
    }  
    
    public string getMaintainenceEndDate() {
           //return m.End_Date__c.format('EEEE, MMMM d, yyyy h:mm a z');
            return releaseWindow.Release_End_Date__c.format();
    } 
    
    
    
}