Youtube Demo/src/objects/Release_Window_Config__c.object
<CustomObject>
    <fields>
        <fullName>Release_End_Date__c</fullName>
        <label>Release End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Release_Start_Date__c</fullName>
        <label>Release Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserLockoutStatus__c</fullName>
        <label>UserLockoutStatus</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lock</fullName>
                </value>
                <value>
                    <fullName>Unlock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release Window Config</label>
    <nameField>
        <label>Release Window Config ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Release Window Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Youtube Demo/src/classes/testReleaseWindowConfigController1.cls
@isTest
public class testReleaseWindowConfigController1 {

    public static testMethod void testReleaseWindowConfigController1() {
           Release_Window_Config__c releaseWindow=new Release_Window_Config__c();
           releaseWindow.Release_Start_Date__c=DateTime.Now();
           releaseWindow.Release_End_Date__c=DateTime.Now().adddays(1);
           releaseWindow.UserLockoutStatus__c='unLock';
           
           insert releaseWindow;
           
           List<Release_Window_Config__c> lstRelWin =new List<Release_Window_Config__c>();
           lstRelWin.add(releaseWindow);
    
           ReleaseWindowConfigController1 controller=new ReleaseWindowConfigController1();
           controller.lstReleaseWindow=lstRelWin;
           controller.saveme();
           
           System.assertNotEquals(null, lstRelWin[0].UserLockoutStatus__c);
           
        
           }
}