Youtube Demo/src/objects/Release_Window_Config__c.object
<CustomObject>
    <fields>
        <fullName>Release_End_Date__c</fullName>
        <label>Release End Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Release_Start_Date__c</fullName>
        <label>Release Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserLockoutStatus__c</fullName>
        <label>UserLockoutStatus</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Lock</fullName>
                </value>
                <value>
                    <fullName>Unlock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Release Window Config</label>
    <nameField>
        <label>Release Window Config ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Release Window Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Youtube Demo/src/classes/ReleaseWindowConfigController1.cls
public class ReleaseWindowConfigController1 {

    public boolean editSection {get;set;}
    public List<Release_Window_Config__c> lstReleaseWindow{get;set;}
    
    public ReleaseWindowConfigController1() {
        ReleaseWindow();
        
    }

  
    public PageReference EdittheSection()
    {
        editSection = true;
        return null;
    }
    
    
    public pagereference saveme()
    {
        try
        {
           update lstReleaseWindow;
           editSection = false;
        }
        catch(Exception e)
        {
            System.debug('Exception occurred '+String.valueOf(e));
        }
        return NULL;
    }
    
    
    public pagereference cancelme()
    {
        editSection = false;
        ReleaseWindow();
        return  null;
    }
    
    
    void ReleaseWindow(){
        lstReleaseWindow =[SELECT Release_End_Date__c,Release_Start_Date__c,UserLockoutStatus__c FROM  Release_Window_Config__c];
    }    


}